### ISSUE TITLE
[issue2] 설계한 테이블( 7가지 )를 적절한 도메인 개념에 따라 분류하도록 한다.

### ISSUE THREAD

**Issue by EooHoSun** [EooHoSun/coupang-eats-order#3]
1. 도메인 모델의 엔티티와 테이블 모델의 엔티티 차이를 이해하고 그에 따라 엔티티 분류와 설계를 진행하도록 한다.
2. ERD상의 테이블 개념에 종속되지않고 Entity와 Value를 이해하여 나눌 수 있도록 Application을 설계하도록 한다.
3. usecase에 입각하여 구현하고자 하는 기능을 에그리거트 단위로 묶어 생각할 수 있도록 한다.

**Comment by apple9rum** [comment]
github issue 에 `#3` 처럼 Numbering 이 되니 굳이 header 는 쓰시지 않아도 되지 않을련지 싶네요. 😀
그리고 DDD 로 개발하시려는 것인가보네요. 좋은 디자인이라고 생각해요.

하나의 이슈에 모든 Domain 작업을 하기 보다는, 하나의 도메인을 하나의 이슈로 처리하시면 좋아요.
이렇게 해야 이슈별로 한가지 기능에 집중해서 작업 할 수 있고 작업량이 줄며, Pull Request 의 reviewer 들이 정확하고 빠른 피드백이 가능해질 수 있어요.

**Comment by EooHoSun** [comment]
안녕하세요 선배님 ^^
리뷰 감사합니다.
제가 사실 DDD방식으로 설계를 해본건 처음이라 관련 서적을 읽고 방향을 잡느라 시간이 좀 걸렸습니다.

이후 가게, 사용자, 리뷰, 주문 으로 4가지의 애그리거트로 분류하여 설계를 진행해보겠습니다.
